### ISSUE TITLE
IDEA OR SUGESTION : Attach standard placement sound.

### ISSUE THREAD

**Issue by Zeekicuss** [enjarai/a-good-place#2]
Hello, I am making a modpack and would like to make some animal crossing like animations for item placements but was wondering how to attach the placement sfx from GC:AC. 
Maybe a way to place or add a new universal placement we can call to whenever?

**Comment by MehVahdJukaar** [comment]
hm would that be a sound that plays on every place indipendent of the standard block placement sound?

**Comment by MehVahdJukaar** [comment]
placement sound can now be added
